
name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_test_unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          python3 test.py
      
      - name: Run programm
        run: |
          python3 main.py

  pytest:
    runs-on: ubuntu-latest
    steps:
      - run: cd pytest/web-page/
      - run: pip install -r requirements.txt
      - run: flask run &
      - run: cd ../tests
      - run: python3 -m pytest
