
name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_test_unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          python3 test.py
      
      - name: Run programm
        run: |
          python3 main.py

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r pytest/requirements.txt
      - run: pytest/web-page flask run &
      - run: ../tests python3 -m pytest
