
name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_test_unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          python3 test.py
      
      - name: Run programm
        run: |
          python3 main.py

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
      - run: sudo apt-get install default-jdk
      - run: sudo apt-get install libxss1 libappindicator1 libindicator7
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo apt install ./google-chrome*.deb
      - run: wget https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar
      - run: pip install -r pytest/requirements.txt
      - run: pytest/web-page flask run &
      - run: pytest