
name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          python3 test.py

      - name: Run pytest
        run: |
        (
        set -x;
        cd pytest/web_page/;
        pip install -r requirements.txt;
        flask run &;
        cd ..;
        cd tests;
        python3 -m pytest;
        )


      
      - name: Run programm
        run: |
          python3 main.py
