
name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          python3 test.py

      - name: Run pytest
        run: (set -x; cd pytest; pip install -r requirements.txt; cd tests; python3 test_math.py -m pytest;)


      
      - name: Run programm
        run: |
          python3 main.py
